apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-status-jogador
  labels:
    app: k8smonster
data:
  nome: {{ .Values.jogador.nome }}
  forma_atual: {{ .Values.jogador.forma_atual }}
  mapa_atual: {{ .Values.jogador.mapa_atual }}
  posicao_x: {{ .Values.jogador.posicao.x | quote }}
  posicao_y: {{ .Values.jogador.posicao.y | quote }}
  # Pega a lista de DNAs e junta tudo com vírgulas
  dnas_capturados: {{ .Values.jogador.inventario.dnas_capturados | join "," | quote }}