jogador:
  nome: "Pioneiro_Cosmico"
  forma_atual: "humano"
  mapa_atual: "cidade_principal"
  posicao:
    x: 10
    y: 15
  inventario:
    dnas_capturados:
      - "gosma_estelar"
      - "espectro_do_vazio"